### ISSUE TITLE
AliEsmaeilli's class checklist

### ISSUE THREAD

**Issue by AliEsmaeili** [githubschool/sleepy-capybara#21]
- [x] Make a branch
- [x] Create a file
- [x] Push out changes
- [x] Create an issue
- [x] Collaborate
- [x] Merge our changes

**Comment by AliEsmaeili** [comment]
close #21
