### ISSUE TITLE
illumination71's class checklist

### ISSUE THREAD

**Issue by illumination71** [githubschool/sleepy-capybara#45]
- [x]  Create a branch
- [x]  Create some commits
- [x]  Open a pull request
- [ ]  Collaborate and comments
- [ ] Merge
